apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  # namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: "{{ .Values.image.repository }}/{{ .Values.orders.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.orders.service.targetPort }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
