apiVersion: v1
kind: Service
metadata:
  name: orders
  # namespace: {{ .Values.namespace }}
  labels:
    app: orders-api
spec:
  type: {{ .Values.orders.service.type }}
  selector:
    app: orders-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.orders.service.port }}
      targetPort: {{ .Values.orders.service.targetPort }}
