# Default values for cast.

app:
  name: cast-pgsql

replicaCount: 1

image:
  repository: postgres
  tag: "12.1-alpine"
  pullPolicy: Always
  
service:
  name: cast-db
  port: 5432

# Pour des raisons de sécurité, il est préférable de ne pas exposer les credentials dans les fichiers de configuration.
# Les valeurs ci-dessous sont fournies à titre d'exemple uniquement et peuvent être remplacées lors du déploiement avec Helm.  
secret:
  stringData:
    POSTGRES_USER: cast_db_username
    POSTGRES_PASSWORD: cast_db_password
    POSTGRES_DB: cast_db_dev

pvc:
  - name: cast-pg-data
    mountPath: /var/lib/postgresql/data
    accessModes: ReadWriteOnce
    storage: 1Gi