apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: pgsql
      protocol: TCP
      port: {{ .Values.service.port }}