apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: "{{ .Values.app.name }}-secret"
          volumeMounts:
{{- range .Values.pvc }}
            - name: {{ .name }}        
              mountPath: {{ .mountPath }}
{{- end }}
  volumeClaimTemplates:
{{- range .Values.pvc }}
    - metadata:
        name: {{ .name }}
      spec:
        accessModes:
          - {{ .accessModes }}
        resources:
          requests:
            storage: {{ .storage }}
{{- end }}