apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  # namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.service.name }}-api"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ .Values.service.name }}-api"
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
