# -----------------------
#  NodePort Service
# -----------------------
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: dev
  labels:
    app: cast-api
spec:
  type: NodePort
  selector:
    app: cast-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30002
---

# -----------------------
# FastAPI Cast Secret
# -----------------------
apiVersion: v1
kind: Secret
metadata:
  name: cast-config-secret
  namespace: dev
stringData:
  DATABASE_URI: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
---

# -----------------------
# FastAPI Cast Deployment
# -----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-api
  template:
    metadata:
      labels:
        app: cast-api
    spec:
      containers:
      - name: cast-api
        image: registry.gitlab.com/jrmclx/jenkins-exam/cast-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: cast-config-secret
      imagePullSecrets:
      - name: regcred
---