# -----------------------
# Ingress vers le Service Gateway
# -----------------------
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: movie-ingress
#   namespace: dev
# spec:
#   ingressClassName: traefik
#   rules:
#   - host: movie.vulgarit.fr
#     http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#              service:
#               name: gateway
#               port:
#                 number: 80

# ---
# -----------------------
# CRD Traefik IngressRoute
# Implémente un fallback qui match tout hostname
# (permet de contourner la nécessité d'un enregistrement DNS à jour)
# -----------------------
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: fallback
#   namespace: dev
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: PathPrefix(`/`)
#       kind: Rule
#       services:
#         - name: gateway
#           port: 80
# ---