# -----------------------
#  Nginx NodePort Service
# -----------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
---

# -----------------------
#  Nginx ConfigMap
# -----------------------
# Pour permettre la mise à jour de la conf depuis le repo de code, on crée le ConfigMap à partir du fichier local
# kubectl create configmap nginx-conf --from-file=default.conf=nginx_config.conf

# -----------------------
#  Nginx Deployment
# -----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: nginx-conf-volume
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: nginx-conf
---