apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
{{- range .Values.configmaps }}
            - name: "{{ .name }}-volume"
{{- range .items }}            
              mountPath: {{ .mountPath }}
              subPath: {{ .key }}
{{- end }}
{{- end }}
      volumes:
{{- range .Values.configmaps }}
        - name: "{{ .name }}-volume"
          configMap:
            name: {{ .name }}
{{- end }}